[project]
name = 'EduChain'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.credential-issuer]
path = 'contracts/credential-issuer.clar'
clarity_version = 2
epoch = 2.5

[contracts.credential-nft]
path = 'contracts/credential-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.institution-integration]
path = 'contracts/institution-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.verification-portal]
path = 'contracts/verification-portal.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
